routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ====================================================
// Auth - route
// ====================================================
Auth::routes();
Route::post('/login', 'Auth\LoginController@login')->name('login.auth');
Route::get('/logout', 'Auth\AuthController@logout')->name('auth.logout');
// ====================================================

Route::get('cari-aset/{param}', 'CariController@index')->name('cari.aset');

Route::group(['middleware' => 'auth'], function(){
    // ====================================================
    // User - route
    // ====================================================
    Route::group(['prefix' => 'user'], function(){
        Route::get('/ubah-password', 'UserController@ubahPassword')->name('user.ubah-password');
        Route::post('/ubah-password', 'UserController@storeUbahPassword')->name('user.ubah-password.store');
    });
    // ====================================================

    // ====================================================
    // Dashboard - route
    // ====================================================
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    // ====================================================

    // ====================================================
    // Master - route
    // ====================================================
    Route::name('master.')->prefix('master')->group(function(){
        Route::group(['middleware' => 'level:1'], function(){
            // ====================================================
            // User - route
            // ====================================================
            Route::group(['prefix' => 'user'], function(){
                Route::get('json/{param}', 'Master\UserController@json')->name('user.json');
                Route::get('active/{param}', 'Master\UserController@active')->name('user.active');
                Route::get('inactive/{param}', 'Master\UserController@inactive')->name('user.inactive');
                Route::put('reset/{param}', 'Master\UserController@resetPassword')->name('user.reset');
            });
            Route::resource('user', 'Master\UserController');
            // ====================================================

            // ====================================================
            // Departemen - route
            // ====================================================
            Route::group(['prefix' => 'departemen'], function(){
                Route::get('json/{param}', 'Master\DepartemenController@json')->name('departemen.json');
            });
            Route::resource('departemen', 'Master\DepartemenController');
            // ====================================================
        });

        // ====================================================
        // Aset - route
        // ====================================================
        Route::group(['prefix' => 'aset'], function(){
            Route::get('json/{param}', 'Master\AsetController@json')->name('aset.json');
            Route::put('active/{param}', 'Master\AsetController@active')->name('aset.active');
            Route::put('inactive/{param}', 'Master\AsetController@inactive')->name('aset.inactive');
            Route::get('qrdownload/{param}', 'Master\AsetController@qrdownload')->name('aset.qrdownload');
        });
        Route::resource('aset', 'Master\AsetController');
        // ====================================================
    });
    // ====================================================

    // ====================================================
    // Fitur - route
    // ====================================================
    Route::name('fitur.')->prefix('fitur')->group(function(){
        Route::group(['middleware' => 'level:2'], function(){
            // ====================================================
            // Aset - route
            // ====================================================
            Route::group(['prefix' => 'aset'], function(){
                Route::get('json/{param}', 'Fitur\AsetController@json')->name('aset.json');
                Route::get('data/{param}', 'Fitur\AsetController@ubahData')->name('aset.ubah.data');
            });
            Route::resource('aset', 'Fitur\AsetController');
            // ====================================================
        });

        Route::group(['middleware' => 'level:1,2,3'], function(){
            // ====================================================
            // Transaksi - route
            // ====================================================
            Route::group(['prefix' => 'transaksi'], function(){
                Route::get('json/{param}', 'Fitur\TransaksiController@json')->name('transaksi.json');
                Route::put('verifikasi/{param}', 'Fitur\TransaksiController@verifikasi')->name('transaksi.verifikasi');
                Route::get('get/aset/{param}', 'Fitur\TransaksiController@getAset')->name('transaksi.get.aset');
                Route::get('check/aset/{param}', 'Fitur\TransaksiController@checkAset')->name('transaksi.check.aset');
            });
            Route::resource('transaksi', 'Fitur\TransaksiController');
            // ====================================================
        });
    });
    // ====================================================

    // ====================================================
    // Laporan - route
    // ====================================================
    Route::name('laporan.')->prefix('laporan')->group(function(){
        Route::group(['middleware' => 'level:1'], function(){
            // ====================================================
            // Aset - route
            // ====================================================
            Route::group(['prefix' => 'aset'], function(){
                Route::get('/', 'Laporan\LaporanAsetController@index')->name('aset.index');
                Route::get('json/{param}', 'Laporan\LaporanAsetController@json')->name('aset.json');
            });
            // ====================================================

            // ====================================================
            // Mutasi - route
            // ====================================================
            Route::group(['prefix' => 'mutasi'], function(){
                Route::get('/', 'Laporan\LaporanMutasiController@index')->name('mutasi.index');
                Route::get('json/{param}', 'Laporan\LaporanMutasiController@json')->name('mutasi.json');
            });
            // ====================================================
        });
    });
    // ====================================================
});

app/Models/Departemen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Departemen extends Model
{
    protected $table = 'departemen';
    protected $guarded = [];

    public $timestamps = false;

    // Relationship
    public function user(){
        return $this->hasMany('App\User', 'departemen_id');
    }

    public function transaksi_awal(){
        return $this->hasMany('App\Models\Transaksi', 'awal_departemen_id');
    }

    public function transaksi_akhir(){
        return $this->hasMany('App\Models\Transaksi', 'akhir_departemen_id');
    }
}

app/Http/Controllers/Master/AsetController.php
<?php

namespace App\Http\Controllers\Master;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
// use SimpleSoftwareIO\QrCode\Facades\QrCode;

use App\Models\Aset;
use App\Models\Departemen;

use Auth;
use QRCode;

class AsetController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_title'] = 'Aset';
        $data['filtering'] = (object)[
            'kondisi' => ['Baru', 'Bekas'],
            'status' => ['Active', 'Inactive'],
        ];

        return view('pages.master.aset.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['page_title'] = 'Tambah Aset';
        $data['departemens'] = Departemen::all();
        $data['aset'] = (object)[
            'id' => '',
            'kode' => '',
            'merk' => '',
            'nama' => '',
            'serial' => '',
            'tanggal_perolehan' => date('Y-m-d'),
            'kondisi' => '',
            'deskripsi' => '',
            'departemen_id' => '',
        ];

        return view('pages.master.aset.form', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'kode' => 'required|string|unique:aset,kode',
            'nama' => 'required|string|min:3',
            'tanggal_perolehan' => 'required|date',
            'kondisi' => 'required',
            'departemen_id' => 'required'
        ])->validate();

        Aset::create([
            'kode' => $request->kode,
            'merk' => $request->merk,
            'nama' => $request->nama,
            'serial' => $request->serial,
            'kondisi' => $request->kondisi,
            'deskripsi' => $request->deskripsi,
            'tanggal_perolehan' => $request->tanggal_perolehan,
            'status' => 1,
            'departemen_id' => $request->departemen_id
        ]);

        return redirect()->route('master.aset.index')->with('success', 'Simpan data berhasil!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $aset = Aset::find($id);
        $data['page_title'] = 'Detail Aset';
        $data['aset'] = $aset;
        $data['depresiasi'] = null;

        // Qrcode
        $path = public_path('img/qr-code/'.$aset->kode.'.png');
        QRCode::text(route('cari.aset', $aset->kode))->setOutfile($path)->png();

        // =================================================
        // Get Penyusutan Data
        // =================================================
        if($aset->harga != null || $aset->nilai_residu != null || $aset->umur != null){
            $result = 0;
            $data_depresiasi = [];
            $between_month = $this->getMonth($aset->tanggal_perolehan);
            $year = date('Y', strtotime($aset->tanggal_perolehan));
            $end_year = date('Y', strtotime($aset->tanggal_perolehan."+".$aset->umur." year"));

            if($between_month[0] != 12){
                while ($year <= $end_year) {
                    $result = 0;
                    $total_month = 0;
                    if($between_month[0] != null){
                        $result = $between_month[0]/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = $between_month[0];
                        $between_month[0] = null;
                    }elseif($year == $end_year){
                        $result = $between_month[1]/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = $between_month[1];
                    }else{
                        $result = 12/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = 12;
                    }

                    $data_depresiasi[] = (object)[
                        "year" => $year,
                        "month" => $total_month,
                        "depresiasi" => ceil($result),
                    ];
                    
                    $year += 1;
                }
            }else{
                $end_year -= 1;
                while ($year <= $end_year) {
                    $result = 0;
                    $total_month = 0;
                    $result = 12/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                    $total_month = 12;

                    $data_depresiasi[] = (object)[
                        "year" => $year,
                        "month" => $total_month,
                        "depresiasi" => ceil($result),
                    ];
                    
                    $year += 1;
                }
            }
            
            $data['depresiasi'] = $data_depresiasi;
        }
        // =================================================

        return view('pages.master.aset.show', $data);
    }

    // Data json
    public function json($param){
        switch ($param) {
            case 'datatable':
                if(Auth::user()->level == 1){
                    $aset = Aset::with('departemen');
                }else{
                    $aset = Aset::with('departemen')->where('departemen_id', Auth::user()->departemen_id);
                }

                return datatables()->of($aset)
                                    ->addIndexColumn()
                                    ->addColumn('status', function($row){
                                        return statusButton($row->status, $row->id);
                                    })
                                    ->addColumn('action', function($row){
                                        $button = '<div class="btn-group" role="group" aria-label="Basic example">';
                                        $button .= '<a href="'.route('master.aset.show', $row->id).'" class="btn btn-sm btn-info"><i class="ti-eye"></i></a>';

                                        if(Auth::user()->level == 1){
                                            $button .= '<a href="'.route('master.aset.edit', $row->id).'" class="btn btn-sm btn-warning"><i class="ti-settings"></i></a>';
                                            $button .= '<button type="button" data-id="'.$row->id.'" class="btn btn-sm btn-danger delete-data"><i class="ti-trash"></i></button>';
                                        }
                                        
                                        $button .= '</div>';
                    
                                        return $button;
                                    })
                                    ->filterColumn('status', function($query,$keyword){
                                        $val = 1;
                                        if($keyword == 'Inactive'){
                                            $val = 0;
                                        }

                                        $query->where('status', $val);
                                    })
                                    ->rawColumns(['status', 'action'])
                                    ->make(true);
                break;
            
            default:
                # code...
                break;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data['page_title'] = 'Edit Aset';
        $data['departemens'] = Departemen::all();
        $data['aset'] = Aset::find($id);

        return view('pages.master.aset.form', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'kode' => 'required|string|unique:aset,kode,'.$id,
            'nama' => 'required|string|min:3',
            'tanggal_perolehan' => 'required|date',
            'kondisi' => 'required',
            'departemen_id' => 'required'
        ])->validate();

        $aset = Aset::find($id);
        $aset->kode = $request->kode;
        $aset->merk = $request->merk;
        $aset->nama = $request->nama;
        $aset->serial = $request->serial;
        $aset->kondisi = $request->kondisi;
        $aset->deskripsi = $request->deskripsi;
        $aset->tanggal_perolehan = $request->tanggal_perolehan;
        $aset->departemen_id = $request->departemen_id;
        $aset->save();

        return redirect()->route('master.aset.index')->with('success', 'Update data berhasil!');
    }

    public function active($id){
        $aset = Aset::find($id);
        $aset->status = 1;
        $aset->save();
    }

    public function inactive($id){
        $aset = Aset::find($id);
        $aset->status = 0;
        $aset->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $aset = Aset::find($id);
        $aset->delete();
    }

    private function getMonth($date){
        $result = [];
        
        // First month
        $month = date('m', strtotime($date));
        $month = 13 - $month;
        $result[] = $month;

        // Last month
        $month = date('m', strtotime($date));
        $month = $month - 1;

resources/views/pages/master/departemen/form.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('master.departemen.index') }}" class="btn btn-success">
          <i class="ti-arrow-circle-left"></i> Kembali
        </a>
      </div>
      <form action="{{ $departemen->id ? route('master.departemen.update', $departemen->id) : route('master.departemen.store') }}" method="POST">
        @csrf
        @if($departemen->id)
          @method('PUT')
        @endif
        <div class="card-body">
          <!-- Form -->
          <div class="form-group">
            <label for="">Nama</label>
            <input type="text" name="nama" class="form-control {{ $errors->has('nama') ? 'is-invalid' : '' }}" value="{{ old('nama') ? old('nama') : $departemen->nama }}">

            <!-- Error -->
            @if($errors->has('nama'))
              <small class="text-danger">
                {{ $errors->first('nama') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">No Telepon</label>
            <input type="text" name="no_telp" class="form-control {{ $errors->has('no_telp') ? 'is-invalid' : '' }}" value="{{ old('no_telp') ? old('no_telp') : $departemen->no_telp }}">

            <!-- Error -->
            @if($errors->has('no_telp'))
              <small class="text-danger">
                {{ $errors->first('no_telp') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Alamat</label>
            <textarea name="alamat" id="alamat" rows="5" class="form-control {{ $errors->has('alamat') ? 'is-invalid' : '' }}">{{ old('alamat') ? old('alamat') : $departemen->alamat }}</textarea>

            <!-- Error -->
            @if($errors->has('alamat'))
              <small class="text-danger">
                {{ $errors->first('alamat') }}
              </small>
            @endif
          </div>
          <!-- Form -->
        </div>

        <div class="card-footer text-right">
          <button type="submit" class="btn btn-primary">
            <i class="ti-save"></i> {{ $departemen->id ? 'Update' : 'Simpan' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@push('script')
<script>
  var app = new Vue({
    el: '#app',
    data: {
      
    },
    methods:{
      
    }
  })
</script>
@endpush

resources/views/pages/master/departemen/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header text-right">
        <a href="{{ route('master.departemen.create') }}" class="btn btn-success">
          <i class="ti-plus"></i> Tambah data departemen
        </a>
      </div>
      <div class="card-body">
        <!-- Datatable -->
        <div class="table-responsive">
          <table id="myDataTable" class="table table-bordered table-striped">
            <thead class="thead-light">
              <tr>
                <th>Nama</th>
                <th>No Telp</th>
                <th>Alamat</th>
                <th>Action</th>
              </tr>
            </thead>
          </table>
        </div>
        <!-- Datatable -->
      </div>
    </div>
  </div>
</div>
@endsection

@push('script')
<script>
  var app = new Vue({
    el: '#app',
    data: {
      table: '',
    },
    methods:{
      // =============================
      // Datatable init
      // =============================
      datatables: function(){
        let _this = this;

        // Clone row on head table
        $('#myDataTable thead tr').clone(true).appendTo('#myDataTable thead');
        
        // Make column search on head table clone column
        $('#myDataTable thead tr:eq(1) th').each( function (i) {
          var title = $(this).text();
          var type = $(this).data('type');
          
          if(title != 'Action'){
            switch (type) {
              case 'select':
                var data = $(this).data('filtering');

                var text = '<select class="form-control">';
                text += '<option value="">Pilih '+ title +'</option>';
                $.each(data, function(index, val){
                  text += '<option value="'+ val +'">'+ val +'</option>';
                });
                text += '</select>';

                $(this).html(text);

                $('select', this).on('change', function(){
                  if(_this.table.column(i).search() !== this.value){
                    _this.table.column(i).search(this.value).draw();
                  }
                });
                break;
            
              default:
                $(this).html( '<input type="text" class="form-control" placeholder="Search '+title+'" />' );

                $('input', this).on('keyup change', function () {
                  if (_this.table.column(i).search() !== this.value) {
                    _this.table.column(i).search(this.value).draw();
                  }
                });
                break;
            }
          }else{
            $(this).html('');
          }
          
        });

        this.table = $('#myDataTable').DataTable({
          order: [[0, "desc"]],
          processing: true,
          serverSide: true,
          orderCellsTop: true,
          fixedHeader: true,
          paging: true,
          lengthChange: true,
          searching: true,
          ordering: true,
          info: true,
          scrollX: true,
          autoWidth: true,
          responsive: true,
          ajax: {
            type: "GET",
            url: "{{ route('master.departemen.json', 'datatable') }}",
            data: {},
          },
          columns: [
            {data: 'nama', name: 'nama', defaultContent: '-'},
            {data: 'no_telp', name: 'no_telp', defaultContent: '-'},
            {data: 'alamat', name: 'alamat', defaultContent: '-'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
        });
      },

      deleteData: function(id){
        let _this = this;
        let link = "{{ route('master.departemen.destroy', ':id') }}";
        link = link.replace(':id', id);

        $.ajax({
          type: "DELETE",
          url: link,
          data: {
            _token: "{{ csrf_token() }}"
          },
          success: function(){
            _this.table.ajax.reload();
          }
        });
      },
    },
    mounted: function(){
      let _this = this;
      this.datatables();

      $(document).on('click', '.delete-data', function(){
        let id = $(this).data('id');
        
        Swal.fire({
          title: 'Apakah anda yakin?',
          text: "Data akan terhapus secara permanen",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Hapus',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            _this.deleteData(id);  
          }
        })
      });
    }
  })
</script>
@endpush