routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ====================================================
// Auth - route
// ====================================================
Auth::routes();
Route::post('/login', 'Auth\LoginController@login')->name('login.auth');
Route::get('/logout', 'Auth\AuthController@logout')->name('auth.logout');
// ====================================================

Route::get('cari-aset/{param}', 'CariController@index')->name('cari.aset');

Route::group(['middleware' => 'auth'], function(){
    // ====================================================
    // User - route
    // ====================================================
    Route::group(['prefix' => 'user'], function(){
        Route::get('/ubah-password', 'UserController@ubahPassword')->name('user.ubah-password');
        Route::post('/ubah-password', 'UserController@storeUbahPassword')->name('user.ubah-password.store');
    });
    // ====================================================

    // ====================================================
    // Dashboard - route
    // ====================================================
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    // ====================================================

    // ====================================================
    // Master - route
    // ====================================================
    Route::name('master.')->prefix('master')->group(function(){
        Route::group(['middleware' => 'level:1'], function(){
            // ====================================================
            // User - route
            // ====================================================
            Route::group(['prefix' => 'user'], function(){
                Route::get('json/{param}', 'Master\UserController@json')->name('user.json');
                Route::get('active/{param}', 'Master\UserController@active')->name('user.active');
                Route::get('inactive/{param}', 'Master\UserController@inactive')->name('user.inactive');
                Route::put('reset/{param}', 'Master\UserController@resetPassword')->name('user.reset');
            });
            Route::resource('user', 'Master\UserController');
            // ====================================================

            // ====================================================
            // Departemen - route
            // ====================================================
            Route::group(['prefix' => 'departemen'], function(){
                Route::get('json/{param}', 'Master\DepartemenController@json')->name('departemen.json');
            });
            Route::resource('departemen', 'Master\DepartemenController');
            // ====================================================
        });

        // ====================================================
        // Aset - route
        // ====================================================
        Route::group(['prefix' => 'aset'], function(){
            Route::get('json/{param}', 'Master\AsetController@json')->name('aset.json');
            Route::put('active/{param}', 'Master\AsetController@active')->name('aset.active');
            Route::put('inactive/{param}', 'Master\AsetController@inactive')->name('aset.inactive');
            Route::get('qrdownload/{param}', 'Master\AsetController@qrdownload')->name('aset.qrdownload');
        });
        Route::resource('aset', 'Master\AsetController');
        // ====================================================
    });
    // ====================================================

    // ====================================================
    // Fitur - route
    // ====================================================
    Route::name('fitur.')->prefix('fitur')->group(function(){
        Route::group(['middleware' => 'level:2'], function(){
            // ====================================================
            // Aset - route
            // ====================================================
            Route::group(['prefix' => 'aset'], function(){
                Route::get('json/{param}', 'Fitur\AsetController@json')->name('aset.json');
                Route::get('data/{param}', 'Fitur\AsetController@ubahData')->name('aset.ubah.data');
            });
            Route::resource('aset', 'Fitur\AsetController');
            // ====================================================
        });

        Route::group(['middleware' => 'level:1,2,3'], function(){
            // ====================================================
            // Transaksi - route
            // ====================================================
            Route::group(['prefix' => 'transaksi'], function(){
                Route::get('json/{param}', 'Fitur\TransaksiController@json')->name('transaksi.json');
                Route::put('verifikasi/{param}', 'Fitur\TransaksiController@verifikasi')->name('transaksi.verifikasi');
                Route::get('get/aset/{param}', 'Fitur\TransaksiController@getAset')->name('transaksi.get.aset');
                Route::get('check/aset/{param}', 'Fitur\TransaksiController@checkAset')->name('transaksi.check.aset');
            });
            Route::resource('transaksi', 'Fitur\TransaksiController');
            // ====================================================
        });
    });
    // ====================================================

    // ====================================================
    // Laporan - route
    // ====================================================
    Route::name('laporan.')->prefix('laporan')->group(function(){
        Route::group(['middleware' => 'level:1'], function(){
            // ====================================================
            // Aset - route
            // ====================================================
            Route::group(['prefix' => 'aset'], function(){
                Route::get('/', 'Laporan\LaporanAsetController@index')->name('aset.index');
                Route::get('json/{param}', 'Laporan\LaporanAsetController@json')->name('aset.json');
            });
            // ====================================================

            // ====================================================
            // Mutasi - route
            // ====================================================
            Route::group(['prefix' => 'mutasi'], function(){
                Route::get('/', 'Laporan\LaporanMutasiController@index')->name('mutasi.index');
                Route::get('json/{param}', 'Laporan\LaporanMutasiController@json')->name('mutasi.json');
            });
            // ====================================================
        });
    });
    // ====================================================
});

app/Models/Aset.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Aset extends Model
{
    protected $table = 'aset';
    protected $guarded = [];

    // Relationship
    public function departemen(){
        return $this->belongsTo('App\Models\Departemen', 'departemen_id');
    }

    public function transaksi_detail(){
        return $this->hasMany('App\Models\TransaksiDetail', 'transaksi_id');
    }
}

app/Http/Controllers/Fitur/AsetController.php
<?php

namespace App\Http\Controllers\Fitur;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Models\Aset;
use App\Models\Departemen;

class AsetController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_title'] = 'Data Aset';
        $data['filtering'] = (object)[
            'kondisi' => ['Baru', 'Bekas'],
            'status' => ['Active', 'Inactive'],
        ];

        return view('pages.fitur.aset.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $aset = Aset::find($id);
        $data['page_title'] = 'Detail Data Aset';
        $data['aset'] = $aset;

        // =================================================
        // Get Penyusutan Data
        // =================================================
        if($aset->harga != null || $aset->nilai_residu != null || $aset->umur != null){
            $result = 0;
            $data_depresiasi = [];
            $between_month = $this->getMonth($aset->tanggal_perolehan);
            $year = date('Y', strtotime($aset->tanggal_perolehan));
            $end_year = date('Y', strtotime($aset->tanggal_perolehan."+".$aset->umur." year"));

            if($between_month[0] != 12){
                while ($year <= $end_year) {
                    $result = 0;
                    $total_month = 0;
                    if($between_month[0] != null){
                        $result = $between_month[0]/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = $between_month[0];
                        $between_month[0] = null;
                    }elseif($year == $end_year){
                        $result = $between_month[1]/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = $between_month[1];
                    }else{
                        $result = 12/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = 12;
                    }

                    $data_depresiasi[] = (object)[
                        "year" => $year,
                        "month" => $total_month,
                        "depresiasi" => ceil($result),
                    ];
                    
                    $year += 1;
                }
            }else{
                $end_year -= 1;
                while ($year <= $end_year) {
                    $result = 0;
                    $total_month = 0;
                    $result = 12/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                    $total_month = 12;

                    $data_depresiasi[] = (object)[
                        "year" => $year,
                        "month" => $total_month,
                        "depresiasi" => ceil($result),
                    ];
                    
                    $year += 1;
                }
            }
            $data['depresiasi'] = $data_depresiasi;
            
        }

        return view('pages.fitur.aset.show', $data);
    }

    // Data json
    public function json($param){
        switch ($param) {
            case 'datatable1':
                $aset = Aset::with('departemen')->where('status', 1)->where('aset_check', 1);

                return datatables()->of($aset)
                                    ->addIndexColumn()
                                    ->addColumn('action', function($row){
                                        $button = '<div class="btn-group" role="group" aria-label="Basic example">';
                                        $button .= '<a href="'.route('fitur.aset.show', $row->id).'" class="btn btn-sm btn-info"><i class="ti-eye"></i></a>';
                                        $button .= '</div>';
                    
                                        return $button;
                                    })
                                    ->rawColumns(['action'])
                                    ->make(true);
                break;

            case 'datatable2':
                $aset = Aset::with('departemen')->where('status', 1)->where('aset_check', 0);

                return datatables()->of($aset)
                                    ->addIndexColumn()
                                    ->addColumn('action', function($row){
                                        $button = '<div class="btn-group" role="group" aria-label="Basic example">';
                                        $button .= '<a href="'.route('fitur.aset.show', $row->id).'" class="btn btn-sm btn-info"><i class="ti-eye"></i></a>';
                                        $button .= '</div>';
                    
                                        return $button;
                                    })
                                    ->rawColumns(['action'])
                                    ->make(true);
                break;
            
            default:
                # code...
                break;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'no_bukti' => 'required',
            'harga' => 'required|numeric',
            'nilai_residu' => 'required|numeric',
            'umur' => 'required|numeric',
        ])->validate();

        $aset = Aset::find($id);
        $aset->no_bukti = $request->no_bukti;
        $aset->harga = $request->harga;
        $aset->nilai_residu = $request->nilai_residu;
        $aset->umur = $request->umur;
        $aset->aset_check = empty($request->aset_check) ? 0 : 1;
        $aset->save();

        return redirect()->route('fitur.aset.index')->with('success', 'Update data berhasil!');
    }

    public function ubahData($id){
        $aset = Aset::find($id);
        $aset->aset_check = 0;
        $aset->save();

        return redirect()->route('fitur.aset.show', $id)->with('info', 'Silahkan update data kembali.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    private function getMonth($date){
        $result = [];
        
        // First month
        $month = date('m', strtotime($date));
        $month = 13 - $month;
        $result[] = $month;

        // Last month
        $month = date('m', strtotime($date));
        $month = $month - 1;
        $result[] = $month;

        return $result;
    }
}

resources/views/pages/master/aset/form.blade.php
@extends('layouts.app')

@push('css')
<!-- Select2 css -->
<link href="{{ asset('assets/plugins/select2/select2.min.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('master.aset.index') }}" class="btn btn-success">
          <i class="ti-arrow-circle-left"></i> Kembali
        </a>
      </div>
      <form action="{{ $aset->id ? route('master.aset.update', $aset->id) : route('master.aset.store') }}" method="POST">
        @csrf
        @if($aset->id)
          @method('PUT')
        @endif
        <div class="card-body">
          <!-- Form -->
          <div class="form-group">
            <label for="">Kode <span class="text-danger">*</span></label>
            <input type="text" name="kode" class="form-control col-md-6 {{ $errors->has('kode') ? 'is-invalid' : '' }}" value="{{ old('kode') ? old('kode') : $aset->kode }}">

            <!-- Error -->
            @if($errors->has('kode'))
              <small class="text-danger">
                {{ $errors->first('kode') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Merk</label>
            <input type="text" name="merk" class="form-control col-md-6 {{ $errors->has('merk') ? 'is-invalid' : '' }}" value="{{ old('merk') ? old('merk') : $aset->merk }}">

            <!-- Error -->
            @if($errors->has('merk'))
              <small class="text-danger">
                {{ $errors->first('merk') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Nama <span class="text-danger">*</span></label>
            <input type="text" name="nama" class="form-control {{ $errors->has('nama') ? 'is-invalid' : '' }}" value="{{ old('nama') ? old('nama') : $aset->nama }}">

            <!-- Error -->
            @if($errors->has('nama'))
              <small class="text-danger">
                {{ $errors->first('nama') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Serial</label>
            <input type="text" name="serial" class="form-control {{ $errors->has('serial') ? 'is-invalid' : '' }}" value="{{ old('serial') ? old('serial') : $aset->serial }}">

            <!-- Error -->
            @if($errors->has('serial'))
              <small class="text-danger">
                {{ $errors->first('serial') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Tanggal Perolehan <span class="text-danger">*</span></label>
            <input type="date" name="tanggal_perolehan" class="form-control col-md-6 {{ $errors->has('tanggal_perolehan') ? 'is-invalid' : '' }}" value="{{ old('tanggal_perolehan') ? old('tanggal_perolehan') : $aset->tanggal_perolehan }}">

            <!-- Error -->
            @if($errors->has('tanggal_perolehan'))
              <small class="text-danger">
                {{ $errors->first('tanggal_perolehan') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Kondisi <span class="text-danger">*</span></label>
            <select name="kondisi" id="kondisi" class="form-control col-md-6 {{ $errors->has('kondisi') ? 'is-invalid' : '' }}">
              <option value="">Pilih Kondisi</option>
              <option value="baru" {{ old('kondisi') == 'baru' || $aset->kondisi == 'baru' ? 'selected' : '' }}>Baru</option>
              <option value="bekas" {{ old('kondisi') == 'bekas' || $aset->kondisi == 'bekas' ? 'selected' : '' }}>Bekas</option>
            </select>

            <!-- Error -->
            @if($errors->has('kondisi'))
              <small class="text-danger">
                {{ $errors->first('kondisi') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Warehouse <span class="text-danger">*</span></label><br>
            <select name="departemen_id" id="departemen_id" class="form-control select2 col-md-6 {{ $errors->has('departemen_id') ? 'is-invalid' : '' }}">
              <option value="">Pilih Warehouse</option>
              @foreach($departemens as $departemen)
                <option value="{{ $departemen->id }}" {{ old('departemen_id') == $departemen->id || $aset->departemen_id == $departemen->id ? 'selected' : '' }}>{{ $departemen->nama }}</option>
              @endforeach
            </select>

            <!-- Error -->
            <br>
            @if($errors->has('departemen_id'))
              <small class="text-danger">
                {{ $errors->first('departemen_id') }}
              </small>
            @endif
          </div>

          <div class="form-group">
            <label for="">Deskripsi</label>
            <textarea name="deskripsi" id="deskripsi" rows="5" class="form-control {{ $errors->has('deskripsi') ? 'is-invalid' : '' }}">{{ old('deskripsi') ? old('deskripsi') : $aset->deskripsi }}</textarea>

            <!-- Error -->
            @if($errors->has('deskripsi'))
              <small class="text-danger">
                {{ $errors->first('deskripsi') }}
              </small>
            @endif
          </div>
          <!-- Form -->
        </div>

        <div class="card-footer">
          <button type="submit" class="btn btn-primary">
            <i class="ti-save"></i> {{ $aset->id ? 'Update' : 'Simpan' }}
          </button>
        </div>
      </form>
    </div>
  </div>
</div>
@endsection

@push('script')
<!-- Select2 Plugin -->
<script src="{{ asset('assets/plugins/select2/select2.min.js') }}"></script>

<script>
  var app = new Vue({
    el: '#app',
    data: {
      
    },
    methods:{
      
    },
    mounted(){
      $('.select2').select2();
    }
  })
</script>
@endpush

resources/views/pages/master/aset/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      @if(Auth::user()->level == 1)
        <div class="card-header text-right">
          <a href="{{ route('master.aset.create') }}" class="btn btn-success">
            <i class="ti-plus"></i> Tambah data aset
          </a>
        </div>
      @else
        <div class="card-header">
          <h5>List Aset</h5>
        </div>
      @endif
      <div class="card-body">
        <!-- Datatable -->
        <div class="table-responsive">
          <table id="myDataTable" class="table table-bordered table-striped">
            <thead class="thead-light">
              <tr>
                <th>Kode</th>
                <th>Nama</th>
                <th data-type="select" data-filtering='{!! parseJson($filtering->kondisi) !!}'>Kondisi</th>
                <th data-type="select" data-filtering='{!! parseJson($filtering->status) !!}'>Status</th>
                <th>Warehouse</th>
                <th>Action</th>
              </tr>
            </thead>
          </table>
        </div>
        <!-- Datatable -->
      </div>
    </div>
  </div>
</div>
@endsection

@push('script')
<script>
  var app = new Vue({
    el: '#app',
    data: {
      table: '',
    },
    methods:{
      // =============================
      // Datatable init
      // =============================
      datatables: function(){
        let _this = this;

        // Clone row on head table
        $('#myDataTable thead tr').clone(true).appendTo('#myDataTable thead');
        
        // Make column search on head table clone column
        $('#myDataTable thead tr:eq(1) th').each( function (i) {
          var title = $(this).text();
          var type = $(this).data('type');
          
          if(title != 'Action'){
            switch (type) {
              case 'select':
                var data = $(this).data('filtering');

                var text = '<select class="form-control">';
                text += '<option value="">Pilih '+ title +'</option>';
                $.each(data, function(index, val){
                  text += '<option value="'+ val +'">'+ val +'</option>';
                });
                text += '</select>';

                $(this).html(text);

                $('select', this).on('change', function(){
                  if(_this.table.column(i).search() !== this.value){
                    _this.table.column(i).search(this.value).draw();
                  }
                });
                break;
            
              default:
                $(this).html( '<input type="text" class="form-control" placeholder="Search '+title+'" />' );

                $('input', this).on('keyup change', function () {
                  if (_this.table.column(i).search() !== this.value) {
                    _this.table.column(i).search(this.value).draw();
                  }
                });
                break;
            }
          }else{
            $(this).html('');
          }
          
        });

        this.table = $('#myDataTable').DataTable({
          order: [[0, "desc"]],
          processing: true,
          serverSide: true,
          orderCellsTop: true,
          fixedHeader: true,
          paging: true,
          lengthChange: true,
          searching: true,
          ordering: true,
          info: true,
          scrollX: true,
          autoWidth: true,
          responsive: true,
          ajax: {
            type: "GET",
            url: "{{ route('master.aset.json', 'datatable') }}",
            data: {},
          },
          columns: [
            {data: 'kode', name: 'kode', defaultContent: '-'},
            {data: 'nama', name: 'nama', defaultContent: '-'},
            {data: 'kondisi', name: 'kondisi', defaultContent: '-'},
            {data: 'status', name: 'status', defaultContent: '-'},
            {data: 'departemen.nama', name: 'departemen.nama', defaultContent: '-'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
        });
      },

      active: function(id){
        let _this = this;
        let link = "{{ route('master.aset.active', ':id') }}";
        link = link.replace(':id', id);

        $.ajax({
          type: "PUT",
          url: link,
          data: {
            _token: "{{ csrf_token() }}"
          },
          success: function(){
            _this.table.ajax.reload();
          }
        });
      },

      inactive: function(id){
        let _this = this;
        let link = "{{ route('master.aset.inactive', ':id') }}";
        link = link.replace(':id', id);

        $.ajax({
          type: "PUT",
          url: link,
          data: {
            _token: "{{ csrf_token() }}"
          },
          success: function(){
            _this.table.ajax.reload();
          }
        });
      },

      deleteData: function(id){
        let _this = this;
        let link = "{{ route('master.aset.destroy', ':id') }}";
        link = link.replace(':id', id);

        $.ajax({
          type: "DELETE",
          url: link,
          data: {
            _token: "{{ csrf_token() }}"
          },
          success: function(){
            _this.table.ajax.reload();
          }
        });
      },
    },
    mounted: function(){
      let _this = this;
      this.datatables();

      // ========================================================
      // Active data on datatable
      // ========================================================
      $(document).on('click', '.btn-active', function(){
        let id = $(this).data('id');
        
        Swal.fire({
          title: 'Aktifkan data?',
          text: "Data akan kembali aktif",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Aktifkan',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            _this.active(id);
          }
        })
      });
      // ========================================================

      // ========================================================
      // Inactive data on datatable
      // ========================================================
      $(document).on('click', '.btn-inactive', function(){
        let id = $(this).data('id');
        
        Swal.fire({
          title: 'Nonaktifkan data?',
          text: "Data akan menjadi nonaktif",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Nonaktifkan',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            _this.inactive(id);
          }
        })
      });
      // ========================================================

      // ========================================================
      // Delete data on datatable
      // ========================================================
      $(document).on('click', '.delete-data', function(){
        let id = $(this).data('id');
        
        Swal.fire({
          title: 'Apakah anda yakin?',
          text: "Data akan terhapus secara permanen",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Hapus',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            _this.deleteData(id);  
          }
        })
      });
      // ========================================================
    }
  })
</script>
@endpush