routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ====================================================
// Auth - route
// ====================================================
Auth::routes();
Route::post('/login', 'Auth\LoginController@login')->name('login.auth');
Route::get('/logout', 'Auth\AuthController@logout')->name('auth.logout');
// ====================================================

Route::get('cari-aset/{param}', 'CariController@index')->name('cari.aset');

Route::group(['middleware' => 'auth'], function(){
    // ====================================================
    // User - route
    // ====================================================
    Route::group(['prefix' => 'user'], function(){
        Route::get('/ubah-password', 'UserController@ubahPassword')->name('user.ubah-password');
        Route::post('/ubah-password', 'UserController@storeUbahPassword')->name('user.ubah-password.store');
    });
    // ====================================================

    // ====================================================
    // Dashboard - route
    // ====================================================
    Route::get('/', 'DashboardController@index')->name('dashboard.index');
    // ====================================================

    // ====================================================
    // Master - route
    // ====================================================
    Route::name('master.')->prefix('master')->group(function(){
        Route::group(['middleware' => 'level:1'], function(){
            // ====================================================
            // User - route
            // ====================================================
            Route::group(['prefix' => 'user'], function(){
                Route::get('json/{param}', 'Master\UserController@json')->name('user.json');
                Route::get('active/{param}', 'Master\UserController@active')->name('user.active');
                Route::get('inactive/{param}', 'Master\UserController@inactive')->name('user.inactive');
                Route::put('reset/{param}', 'Master\UserController@resetPassword')->name('user.reset');
            });
            Route::resource('user', 'Master\UserController');
            // ====================================================

            // ====================================================
            // Departemen - route
            // ====================================================
            Route::group(['prefix' => 'departemen'], function(){
                Route::get('json/{param}', 'Master\DepartemenController@json')->name('departemen.json');
            });
            Route::resource('departemen', 'Master\DepartemenController');
            // ====================================================
        });

        // ====================================================
        // Aset - route
        // ====================================================
        Route::group(['prefix' => 'aset'], function(){
            Route::get('json/{param}', 'Master\AsetController@json')->name('aset.json');
            Route::put('active/{param}', 'Master\AsetController@active')->name('aset.active');
            Route::put('inactive/{param}', 'Master\AsetController@inactive')->name('aset.inactive');
            Route::get('qrdownload/{param}', 'Master\AsetController@qrdownload')->name('aset.qrdownload');
        });
        Route::resource('aset', 'Master\AsetController');
        // ====================================================
    });
    // ====================================================

    // ====================================================
    // Fitur - route
    // ====================================================
    Route::name('fitur.')->prefix('fitur')->group(function(){
        Route::group(['middleware' => 'level:2'], function(){
            // ====================================================
            // Aset - route
            // ====================================================
            Route::group(['prefix' => 'aset'], function(){
                Route::get('json/{param}', 'Fitur\AsetController@json')->name('aset.json');
                Route::get('data/{param}', 'Fitur\AsetController@ubahData')->name('aset.ubah.data');
            });
            Route::resource('aset', 'Fitur\AsetController');
            // ====================================================
        });

        Route::group(['middleware' => 'level:1,2,3'], function(){
            // ====================================================
            // Transaksi - route
            // ====================================================
            Route::group(['prefix' => 'transaksi'], function(){
                Route::get('json/{param}', 'Fitur\TransaksiController@json')->name('transaksi.json');
                Route::put('verifikasi/{param}', 'Fitur\TransaksiController@verifikasi')->name('transaksi.verifikasi');
                Route::get('get/aset/{param}', 'Fitur\TransaksiController@getAset')->name('transaksi.get.aset');
                Route::get('check/aset/{param}', 'Fitur\TransaksiController@checkAset')->name('transaksi.check.aset');
            });
            Route::resource('transaksi', 'Fitur\TransaksiController');
            // ====================================================
        });
    });
    // ====================================================

    // ====================================================
    // Laporan - route
    // ====================================================
    Route::name('laporan.')->prefix('laporan')->group(function(){
        Route::group(['middleware' => 'level:1'], function(){
            // ====================================================
            // Aset - route
            // ====================================================
            Route::group(['prefix' => 'aset'], function(){
                Route::get('/', 'Laporan\LaporanAsetController@index')->name('aset.index');
                Route::get('json/{param}', 'Laporan\LaporanAsetController@json')->name('aset.json');
            });
            // ====================================================

            // ====================================================
            // Mutasi - route
            // ====================================================
            Route::group(['prefix' => 'mutasi'], function(){
                Route::get('/', 'Laporan\LaporanMutasiController@index')->name('mutasi.index');
                Route::get('json/{param}', 'Laporan\LaporanMutasiController@json')->name('mutasi.json');
            });
            // ====================================================
        });
    });
    // ====================================================
});

app/Models/Transaksi.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Transaksi extends Model
{
    protected $table = 'transaksi';
    protected $guarded = [];

    // Relationship
    public function user(){
        return $this->belongsTo('App\User', 'user_id');
    }

    public function transaksi_detail(){
        return $this->hasMany('App\Models\TransaksiDetail', 'transaksi_id');
    }

    public function departemen_awal(){
        return $this->belongsTo('App\Models\Departemen', 'awal_departemen_id');
    }

    public function departemen_akhir(){
        return $this->belongsTo('App\Models\Departemen', 'akhir_departemen_id');
    }
}

app/Http/Controllers/Fitur/AsetController.php
<?php

namespace App\Http\Controllers\Fitur;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

use App\Models\Aset;
use App\Models\Departemen;

class AsetController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['page_title'] = 'Data Aset';
        $data['filtering'] = (object)[
            'kondisi' => ['Baru', 'Bekas'],
            'status' => ['Active', 'Inactive'],
        ];

        return view('pages.fitur.aset.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $aset = Aset::find($id);
        $data['page_title'] = 'Detail Data Aset';
        $data['aset'] = $aset;

        // =================================================
        // Get Penyusutan Data
        // =================================================
        if($aset->harga != null || $aset->nilai_residu != null || $aset->umur != null){
            $result = 0;
            $data_depresiasi = [];
            $between_month = $this->getMonth($aset->tanggal_perolehan);
            $year = date('Y', strtotime($aset->tanggal_perolehan));
            $end_year = date('Y', strtotime($aset->tanggal_perolehan."+".$aset->umur." year"));

            if($between_month[0] != 12){
                while ($year <= $end_year) {
                    $result = 0;
                    $total_month = 0;
                    if($between_month[0] != null){
                        $result = $between_month[0]/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = $between_month[0];
                        $between_month[0] = null;
                    }elseif($year == $end_year){
                        $result = $between_month[1]/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = $between_month[1];
                    }else{
                        $result = 12/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                        $total_month = 12;
                    }

                    $data_depresiasi[] = (object)[
                        "year" => $year,
                        "month" => $total_month,
                        "depresiasi" => ceil($result),
                    ];
                    
                    $year += 1;
                }
            }else{
                $end_year -= 1;
                while ($year <= $end_year) {
                    $result = 0;
                    $total_month = 0;
                    $result = 12/12 * ($aset->harga - $aset->nilai_residu) / $aset->umur;
                    $total_month = 12;

                    $data_depresiasi[] = (object)[
                        "year" => $year,
                        "month" => $total_month,
                        "depresiasi" => ceil($result),
                    ];
                    
                    $year += 1;
                }
            }
            $data['depresiasi'] = $data_depresiasi;
            
        }

        return view('pages.fitur.aset.show', $data);
    }

    // Data json
    public function json($param){
        switch ($param) {
            case 'datatable1':
                $aset = Aset::with('departemen')->where('status', 1)->where('aset_check', 1);

                return datatables()->of($aset)
                                    ->addIndexColumn()
                                    ->addColumn('action', function($row){
                                        $button = '<div class="btn-group" role="group" aria-label="Basic example">';
                                        $button .= '<a href="'.route('fitur.aset.show', $row->id).'" class="btn btn-sm btn-info"><i class="ti-eye"></i></a>';
                                        $button .= '</div>';
                    
                                        return $button;
                                    })
                                    ->rawColumns(['action'])
                                    ->make(true);
                break;

            case 'datatable2':
                $aset = Aset::with('departemen')->where('status', 1)->where('aset_check', 0);

                return datatables()->of($aset)
                                    ->addIndexColumn()
                                    ->addColumn('action', function($row){
                                        $button = '<div class="btn-group" role="group" aria-label="Basic example">';
                                        $button .= '<a href="'.route('fitur.aset.show', $row->id).'" class="btn btn-sm btn-info"><i class="ti-eye"></i></a>';
                                        $button .= '</div>';
                    
                                        return $button;
                                    })
                                    ->rawColumns(['action'])
                                    ->make(true);
                break;
            
            default:
                # code...
                break;
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'no_bukti' => 'required',
            'harga' => 'required|numeric',
            'nilai_residu' => 'required|numeric',
            'umur' => 'required|numeric',
        ])->validate();

        $aset = Aset::find($id);
        $aset->no_bukti = $request->no_bukti;
        $aset->harga = $request->harga;
        $aset->nilai_residu = $request->nilai_residu;
        $aset->umur = $request->umur;
        $aset->aset_check = empty($request->aset_check) ? 0 : 1;
        $aset->save();

        return redirect()->route('fitur.aset.index')->with('success', 'Update data berhasil!');
    }

    public function ubahData($id){
        $aset = Aset::find($id);
        $aset->aset_check = 0;
        $aset->save();

        return redirect()->route('fitur.aset.show', $id)->with('info', 'Silahkan update data kembali.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    private function getMonth($date){
        $result = [];
        
        // First month
        $month = date('m', strtotime($date));
        $month = 13 - $month;
        $result[] = $month;

        // Last month
        $month = date('m', strtotime($date));
        $month = $month - 1;
        $result[] = $month;

        return $result;
    }
}

resources/views/pages/fitur/transaksi/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      @if(Auth::user()->level == 1)
        <div class="card-header text-right">
          <a href="{{ route('fitur.transaksi.create') }}" class="btn btn-success">
            <i class="ti-plus"></i> Tambah data transaksi
          </a>
        </div>
      @else
        <div class="card-header">
          <h5>List Transaksi / Mutasi Aset</h5>
        </div>
      @endif
      <div class="card-body">
        <!-- Datatable -->
        <div class="table-responsive">
          <table id="myDataTable" class="table table-bordered table-striped">
            <thead class="thead-light">
              <tr>
                <th>Tanggal</th>
                <th data-type="select" data-filtering='{!! parseJson($filtering->verifikasi) !!}'>Verifikasi</th>
                <th>Awal Departemen</th>
                <th>Akhir Departemen</th>
                <th data-type="select" data-filtering='{!! parseJson($filtering->status) !!}'>Status</th>
                <th>Action</th>
              </tr>
            </thead>
          </table>
        </div>
        <!-- Datatable -->
      </div>
    </div>
  </div>
</div>
@endsection

@push('script')
<script>
  var app = new Vue({
    el: '#app',
    data: {
      table: '',
    },
    methods:{
      // =============================
      // Datatable init
      // =============================
      datatables: function(){
        let _this = this;

        // Clone row on head table
        $('#myDataTable thead tr').clone(true).appendTo('#myDataTable thead');
        
        // Make column search on head table clone column
        $('#myDataTable thead tr:eq(1) th').each( function (i) {
          var title = $(this).text();
          var type = $(this).data('type');
          
          if(title != 'Action'){
            switch (type) {
              case 'select':
                var data = $(this).data('filtering');

                var text = '<select class="form-control">';
                text += '<option value="">Pilih '+ title +'</option>';
                $.each(data, function(index, val){
                  text += '<option value="'+ val +'">'+ val +'</option>';
                });
                text += '</select>';

                $(this).html(text);

                $('select', this).on('change', function(){
                  if(_this.table.column(i).search() !== this.value){
                    _this.table.column(i).search(this.value).draw();
                  }
                });
                break;
            
              default:
                $(this).html( '<input type="text" class="form-control" placeholder="Search '+title+'" />' );

                $('input', this).on('keyup change', function () {
                  if (_this.table.column(i).search() !== this.value) {
                    _this.table.column(i).search(this.value).draw();
                  }
                });
                break;
            }
          }else{
            $(this).html('');
          }
          
        });

        this.table = $('#myDataTable').DataTable({
          order: [[0, "desc"]],
          processing: true,
          serverSide: true,
          orderCellsTop: true,
          fixedHeader: true,
          paging: true,
          lengthChange: true,
          searching: true,
          ordering: true,
          info: true,
          scrollX: true,
          autoWidth: true,
          responsive: true,
          ajax: {
            type: "GET",
            url: "{{ route('fitur.transaksi.json', 'datatable') }}",
            data: {},
          },
          columns: [
            {data: 'tanggal_transaksi', name: 'tanggal_transaksi', defaultContent: '-'},
            {data: 'verifikasi_status', name: 'verifikasi_status', defaultContent: '-'},
            {data: 'departemen_awal.nama', name: 'departemen_awal.nama', defaultContent: '-'},
            {data: 'departemen_akhir.nama', name: 'departemen_akhir.nama', defaultContent: '-'},
            {data: 'status', name: 'status', defaultContent: '-'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
        });
      },

      deleteData: function(id){
        let _this = this;
        let link = "{{ route('fitur.transaksi.destroy', ':id') }}";
        link = link.replace(':id', id);

        $.ajax({
          type: "DELETE",
          url: link,
          data: {
            _token: "{{ csrf_token() }}"
          },
          success: function(){
            _this.table.ajax.reload();
          }
        });
      },
    },
    mounted: function(){
      let _this = this;
      this.datatables();

      // ========================================================
      // Delete data on datatable
      // ========================================================
      $(document).on('click', '.delete-data', function(){
        let id = $(this).data('id');
        
        Swal.fire({
          title: 'Apakah anda yakin?',
          text: "Data akan terhapus secara permanen",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Hapus',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            _this.deleteData(id);  
          }
        })
      });
      // ========================================================
    }
  })
</script>
@endpush

resources/views/pages/fitur/transaksi/show.blade.php
@extends('layouts.app')

@push('css')
<!-- Select2 css -->
<link href="{{ asset('assets/plugins/select2/select2.min.css') }}" rel="stylesheet">
@endpush

@section('content')
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="card-header">
        <a href="{{ route('fitur.transaksi.index') }}" class="btn btn-success">
          <i class="ti-arrow-circle-left"></i> Kembali
        </a>

        @if(Auth::user()->level == 1)
          <a href="{{ route('fitur.transaksi.edit', $transaksi->id) }}" class="btn btn-info">
            <i class="ti-pencil-alt"></i> Ubah Data
          </a>
        @endif
      </div>
      
      <div class="card-body">
        <h2>Transaksi <br><small>Mutasi barang</small></h2>
        <div class="mt-4">
          <h5><span class="badge badge-primary">{{ longDateFormat($transaksi->tanggal_transaksi) }}</span></h5>
          <div class="row">
            <div class="col-md-6">
              <div class="row">
                <div class="col-sm-6">
                  <h5>Dari <i class="ti-arrow-circle-right"></i></h5>
                  <p>
                    {{ $transaksi->departemen_awal->nama }}
                    <hr>
                    <i class="ti-themify-favicon"></i> {{ $transaksi->departemen_awal->no_telp }}<br>
                    <i class="ti-location-pin"></i> {{ $transaksi->departemen_awal->alamat }}
                  </p>
                </div>
                <div class="col-sm-6">
                  <h5><i class="ti-arrow-circle-left"></i> Penerima</h5>
                  <p>{{ $transaksi->departemen_akhir->nama }}</p>
                  <hr>
                  <i class="ti-themify-favicon"></i> {{ $transaksi->departemen_akhir->no_telp }}<br>
                  <i class="ti-location-pin"></i> {{ $transaksi->departemen_akhir->alamat }}
                </div>
              </div>

              <div class="content1 mt-3">
                <b>Kondisi</b>
                <p>{{ $transaksi->kondisi }}</p>
                <b>Status</b>
                <p>{!! statusAset($transaksi->status) !!}</p>
                <b>Pembuat</b>
                <p>{{ $transaksi->user->nama }}</p>
                <b>Verifikasi Status</b>
                <p>{!! statusVerifikasi($transaksi->verifikasi_status) !!}</p>
              </div>
            </div>

            <div class="col-md-6">
              <h5>List Aset</h5>
              <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Jika ada kesalahan data mohon hubungi kantor pusat <b>(General Affair)</b>.
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="table-responsive">
                <table class="table table-striped table-bordered">
                  <thead>
                    <tr>
                      <th>No</th>
                      <th>Kode</th>
                      <th>Nama</th>
                      <th>Kondisi</th>
                      <th>Check Aset</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    @php $no = 1; @endphp
                    @foreach($transaksi->transaksi_detail as $row)
                      <tr>
                        <td>{{ $no++ }}</td>
                        <td>{{ $row->aset->kode }}</td>
                        <td>{{ $row->aset->nama }}</td>
                        <td>{{ ucwords($row->aset->kondisi) }}</td>
                        <td><input type="checkbox" name="check_aset[]" class="check-aset" value="{{ $row->id }}" {{ $row->status == 1 ? 'checked' : '' }} {{ $transaksi->verifikasi_status == 1 || $transaksi->departemen_awal->id == Auth::user()->departemen_id ? 'disabled' : '' }}></td>
                        <td>
                          <button class="btn btn-info btn-sm" @click="getAset({{ $row->aset->id }})" data-toggle="modal" data-target="#modalAset"><i class="ti-eye"></i></button>
                        </td>
                      </tr>
                    @endforeach
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

      @if(Auth::user()->departemen->id == $transaksi->akhir_departemen_id && $transaksi->verifikasi_status == 0)
      <div class="card-footer text-right">
        <button class="btn btn-primary" @click="verifikasi({{ $transaksi->id }})"><i class="ti-check-box"></i> Verifikasi</button>
      </div>
      @endif
    </div>
  </div>
</div>
@endsection

@section('modal')
<!-- Modal -->
<div class="modal fade" id="modalAset" tabindex="-1" aria-labelledby="modalAsetLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalAsetLabel">Detail Aset</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <b>Kode</b>
        <p class="aset-kode">@{{ aset.kode }}</p>
        <hr>
        <b>Merk</b>
        <p class="aset-merk">@{{ aset.merk }}</p>
        <hr>
        <b>Nama</b>
        <p class="aset-nama">@{{ aset.nama }}</p>
        <hr>
        <b>Serial</b>
        <p class="aset-serial">@{{ aset.serial }}</p>
        <hr>
        <b>Tanggal Perolehan</b>
        <p class="aset-tanggal-perolehan">@{{ aset.tanggal_perolehan }}</p>
        <hr>
        <b>Kondisi</b>
        <p class="aset-kondisi">@{{ aset.kondisi }}</p>
        <hr>
        <b>Warehouse</b>
        <p class="aset-departemen">@{{ aset.departemen.nama }}</p>
        <hr>
        <b>Deskripsi</b>
        <p class="aset-deskripsi">@{{ aset.deskripsi }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
@endsection

@push('script')
<!-- Select2 Plugin -->
<script src="{{ asset('assets/plugins/select2/select2.min.js') }}"></script>

<!-- Select2 Init -->
<script src="{{ asset('assets/js/pages/forms-select2.init.js') }}"></script>

<script>
  var app = new Vue({
    el: '#app',
    data: {
      aset: {
        departemen: {}
      }
    },
    methods:{
      getAset(aset_id){
        let _this = this;
        $.ajax({
          url: "{{ route('fitur.transaksi.get.aset', ':id') }}".replace(":id", aset_id),
          type: "GET",
          dataType: "JSON",
          success: function(response){
            _this.aset = response;
          }
        })
      },

      checkAset(type, id){
        $.ajax({
          url: "{{ route('fitur.transaksi.check.aset', ':id') }}".replace(":id", id),
          type: "GET",
          data: {
            type: type
          },
          success: function(response){
            toastr.success(response.message);
          }
        });
      },

      verifikasi(id){
        Swal.fire({
          title: 'Apakah anda yakin ingin verifikasi?',
          text: "Data akan dimasukkan kedalam warehouse yang sesuai.",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Verifikasi',
          cancelButtonText: 'Batal',
        }).then((result) => {
          if (result.value) {
            $.ajax({
              url: "{{ route('fitur.transaksi.verifikasi', ':id') }}".replace(":id", id),
              type: "PUT",
              data: {
                _token: "{{ csrf_token() }}"
              },
              success: function(response){
                if(response.status){
                  location.reload();
                }else{
                  toastr.warning(response.message);
                }
              }
            });
          }
        })
      }
    },
    mounted(){
      let _this = this;

      // ===================================
      // Check Aset
      // ===================================
      $(document).on('click', '.check-aset', function(){
        let val = $(this).val();
        if(this.checked){
          _this.checkAset(1, val);
        }else{
          _this.checkAset(0, val);
        }
      });
      // ===================================
    }
  })
</script>
@endpush